main:
    path: /
    controller: App\Controller\ContentController::buildMain

account:
    path: /account
    controller: App\Controller\ContentController::buildAccount

user:
    path: /user
    controller: App\Controller\ContentController::buildUser

operator:
    path: /operator
    controller: App\Controller\ContentController::buildOperator