user:
    path: /user
    controller: App\Controller\UserController::buildUser

operator_task_edit:
    path: /operator/task/{id}
    controller: App\Controller\OperatorController::buildTaskEdit

operator_account_edit:
    path: /operator/account/{id}
    controller: App\Controller\OperatorController::buildAccountEdit

operator_credential_edit:
    path: /operator/credential/{id}
    controller: App\Controller\OperatorController::buildCredentialEdit

#task_save:
#    path: /manager/save/task
#    controller: App\Controller\ManagerController::saveTask
