user:
    path: /user
    controller: App\Controller\UserController::buildUser

user.account.detail:
    path: /user/game/{id}
    controller: App\Controller\UserController::buildGameDetail

operator_account_edit:
    path: /operator/account/{id}
    controller: App\Controller\OperatorController::buildAccountEdit

user.basket:
    path: /basket
    controller: App\Controller\UserController::buildBasket

#task_save:
#    path: /manager/save/task
#    controller: App\Controller\ManagerController::saveTask
